### ISSUE TITLE
Doubled image count

### ISSUE THREAD

**Issue by tomanatura** [akizor/PhotoSwipe-Gallery-Improvement#2]
Hello, 
thanks you for your PhotoSwipe-Gallery-Improvement! 
I need embed every two `<figure>` in an extra `<div>`. Everything works fine, only if I click on thumb to open Photoswipe it double images and it goes two times trough every extra `<div>`. Look to Codepen demo https://codepen.io/gorem/pen/zawmOp Instead of 4 images it loads 8 and it loop like: 1 > 2 > 1 > 2 > 3 > 4 > 3 > 4 is there way to fix that? 
Thanks you

**Comment by akizor** [comment]
You have 3 options here:
1. Put all your `figure` elements inside a wrapper and change them using css or class names
2. Modify the function that searches for the closest other `figure` element inside your DOM. That function is called `closest` and searches for figure starting from parent element. In normal use, parent element is the main wrapper for all `figure`s. In your case, is the `.flex` div. That's why you are getting doubled images.
3. Check this [issue](https://github.com/akizor/PhotoSwipe-Gallery-Improvement/issues/1). You can see in the demo that he's using a wrapper for each owl element. Probably might help you

**Comment by tomanatura** [comment]
Thanks you. I think option 2 is the best to my needs. Ive tried play with "FIGURE", but it doesnt work, so did you mean this part of code? 
`// find nearest parent element
	var closest = function closest(el, fn) {
		return el && ( fn(el) ? el : closest(el.parentNode, fn) );
	};
`
Im really basic in JS (almost nothing), may I ask you for an example, what did you mean?
Thanks you very much
